### ISSUE TITLE
[Feature Request] Option to disable when not near a bank

### ISSUE THREAD

**Issue by Xylot** [josmoo/AmuletOfChemistryAlerter#3]
The plugin was notifying me while killing Muspah due to having Ancient Essence and Ancient Brews in the inventory. An option (or possibly the default) to only trigger the notification while near a bank would be awesome!

**Comment by josmoo** [comment]
Sorry I've been busy- better late than never I hope. Updated in [latest commit](https://github.com/josmoo/AmuletOfChemistryAlerter/commit/ab62b82d33ba3eef2a759b4fa5e1d3591c58374a)
